# Generated by Django 4.2.15 on 2024-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=2)),
                ('numeroDocumento', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('contrasena', models.CharField(max_length=13)),
                ('fechaActuaContrasena', models.DateField()),
                ('fechaInicioSesion', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=150)),
                ('campoNotificar', models.BooleanField(default=False)),
                ('nombre_inicioSesion', models.CharField(max_length=10)),
                ('estado_InicioSesion', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'inactivo')], max_length=20)),
            ],
        ),
    ]
