# Generated by Django 4.2.15 on 2024-08-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_remove_usuario_nombre_iniciosesion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_InicioSesion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20),
        ),
    ]
