# Generated by Django 4.2.15 on 2024-09-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosobreescrito',
            name='tipoDocumento',
            field=models.CharField(choices=[('TI', 'TI'), ('CC', 'CC'), ('CE', 'CE')], default='CC', max_length=2),
        ),
    ]
